<?php

use App\Models\Permission;
use App\User;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect("/api/documentation");
    // $user= new User();
    // $user->name = "qasem";
    // $user->email = "qasem@gmail.com";
    // $user->password = bcrypt("123456");
    // $user->save();

    return view('welcome');
});

// Route::get('/set_permissions', function () {
//     Permission::insert(
//         [
//             ['title' => 'read_categories',
//                 'descriptiosn' => 'توضیحات مشاهده دسته بندی ها',
//                 'path' => 'api/admin/categories',
//                 'method' => 'get',
//                 'arrange' => '1',
//                 'category' => 'categories'],
//             ['title' => 'create_category',
//                 'descriptiosn' => 'افزودن دسته بندی',
//                 'path' => 'api/admin/categories',
//                 'method' => 'post',
//                 'arrange' => '1',
//                 'category' => 'categories'],
//             ['title' => 'read_category',
//                 'descriptiosn' => 'دریافت تکی دسته بندی',
//                 'path' => 'api/admin/categories/{id}',
//                 'method' => 'get',
//                 'arrange' => '1',
//                 'category' => 'categories'],
//             ['title' => 'update_category',
//                 'descriptiosn' => 'ویرایش دسته بندی',
//                 'path' => 'api/admin/categories/{id}',
//                 'method' => 'put',
//                 'arrange' => '1',
//                 'category' => 'categories'],
//             ['title' => 'delete_category',
//                 'descriptiosn' => 'حذف دسته بندی',
//                 'path' => 'api/admin/categories/{id}',
//                 'method' => 'delete',
//                 'arrange' => '1',
//                 'category' => 'categories'],
//             ['title' => 'read_category_attrs',
//                 'descriptiosn' => 'دریاقت ویژگیهای دسته بندی',
//                 'path' => 'api/admin/categories/{categoryId}/attributes',
//                 'method' => 'get',
//                 'arrange' => '2',
//                 'category' => 'categories'],
//             ['title' => 'create_category_attr',
//                 'descriptiosn' => 'تعریف ویژگی برای دسته بندی',
//                 'path' => 'api/admin/categories/{categoryId}/attributes',
//                 'method' => 'post',
//                 'arrange' => '2',
//                 'category' => 'categories'],
//             ['title' => 'read_category_attr',
//                 'descriptiosn' => 'دریاقت یک ویژگی از دسته بندی',
//                 'path' => 'api/admin/categories/attributes/{id}',
//                 'method' => 'get',
//                 'arrange' => '2',
//                 'category' => 'categories'],
//             ['title' => 'update_category_attr',
//                 'descriptiosn' => 'ویرایش ویژگی هر دسته بندی',
//                 'path' => 'api/admin/categories/attributes/{id}',
//                 'method' => 'put',
//                 'arrange' => '2',
//                 'category' => 'categories'],
//             ['title' => 'delete_category_attr',
//                 'descriptiosn' => 'حذف ویژگی مربوط به دسته بندی',
//                 'path' => 'api/admin/categories/attributes/{id}',
//                 'method' => 'delete',
//                 'arrange' => '2',
//                 'category' => 'categories'],
//             ['title' => 'read_products',
//                 'descriptiosn' => 'مشاهده محصولات',
//                 'path' => 'api/admin/products',
//                 'method' => 'get',
//                 'arrange' => '3',
//                 'category' => 'محصولات'],
//             ['title' => 'read_products_title',
//                 'descriptiosn' => 'دریافت همه عناوین محصولات',
//                 'path' => 'api/admin/products/all_titles',
//                 'method' => 'get',
//                 'arrange' => '3',
//                 'category' => 'محصولات'],
//             ['title' => 'create_product',
//                 'descriptiosn' => 'افزودن محصول جدید',
//                 'path' => 'api/admin/products',
//                 'method' => 'post',
//                 'arrange' => '3',
//                 'category' => 'محصولات'],
//             ['title' => 'read_product',
//                 'descriptiosn' => 'دریافت یک محصول',
//                 'path' => 'api/admin/products/{id}',
//                 'method' => 'get',
//                 'arrange' => '3',
//                 'category' => 'محصولات'],
//             ['title' => 'exist_product_title',
//                 'descriptiosn' => 'بررسی وجود عنوان محصول',
//                 'path' => 'api/admin/products/title_is_exist/{title}',
//                 'method' => 'get',
//                 'arrange' => '3',
//                 'category' => 'محصولات'],
//             ['title' => 'update_product',
//                 'descriptiosn' => 'ویرایش محصول',
//                 'path' => 'api/admin/products/{id}',
//                 'method' => 'put',
//                 'arrange' => '3',
//                 'category' => 'محصولات'],
//             ['title' => 'delete_product',
//                 'descriptiosn' => 'حذف محصول',
//                 'path' => 'api/admin/products/{id}',
//                 'method' => 'delete',
//                 'arrange' => '3',
//                 'category' => 'محصولات'],
//             ['title' => 'create_product_attr',
//                 'descriptiosn' => 'افزودن ویژگی محصول',
//                 'path' => 'api/admin/products/{id}/add_attr',
//                 'method' => 'post',
//                 'arrange' => '4',
//                 'category' => 'محصولات'],
//             ['title' => 'read_product_attrs',
//                 'descriptiosn' => 'دریافت ویژگی محصول',
//                 'path' => 'api/admin/products/{id}/get_attr',
//                 'method' => 'get',
//                 'arrange' => '4',
//                 'category' => 'محصولات'],
//             ['title' => 'create_product_image',
//                 'descriptiosn' => 'افزودن تصویر محصول',
//                 'path' => 'api/admin/products/{id}/add_image',
//                 'method' => 'post',
//                 'arrange' => '5',
//                 'category' => 'محصولات'],
//             ['title' => 'delete_product_image',
//                 'descriptiosn' => 'حذف تصویر محصول',
//                 'path' => 'api/admin/products/gallery/{imageId}',
//                 'method' => 'delete',
//                 'arrange' => '5',
//                 'category' => 'محصولات'],
//             ['title' => 'default_product_image',
//                 'descriptiosn' => 'تنظیم تصویر پیشفرض',
//                 'path' => 'api/admin/products/gallery/set_main/{imageId}',
//                 'method' => 'get',
//                 'arrange' => '5',
//                 'category' => 'محصولات'],
//             ['title' => 'read_colors',
//                 'descriptiosn' => 'مشاهده لیست رنگ ها',
//                 'path' => 'api/admin/colors',
//                 'method' => 'get',
//                 'arrange' => '6',
//                 'category' => 'رنگ ها'],
//             ['title' => 'create_color',
//                 'descriptiosn' => 'افزودن رنگ جدید',
//                 'path' => 'api/admin/colors',
//                 'method' => 'post',
//                 'arrange' => '6',
//                 'category' => 'رنگ ها'],
//             ['title' => 'read_color',
//                 'descriptiosn' => 'مشاهده یک رنگ',
//                 'path' => 'api/admin/colors/{id}',
//                 'method' => 'get',
//                 'arrange' => '6',
//                 'category' => 'رنگ ها'],
//             ['title' => 'update_color',
//                 'descriptiosn' => 'ویرایش رنگ',
//                 'path' => 'api/admin/colors/{id}',
//                 'method' => 'put',
//                 'arrange' => '6',
//                 'category' => 'رنگ ها'],
//             ['title' => 'delete_color',
//                 'descriptiosn' => 'حذف رنگ ها',
//                 'path' => 'api/admin/colors/{id}',
//                 'method' => 'delete',
//                 'arrange' => '6',
//                 'category' => 'رنگ ها'],
//             ['title' => 'read_brands',
//                 'descriptiosn' => 'مشاهده برند ها',
//                 'path' => 'api/admin/brands',
//                 'method' => 'get',
//                 'arrange' => '7',
//                 'category' => 'برند ها'],
//             ['title' => 'create_brand',
//                 'descriptiosn' => 'افزودن برند جدید',
//                 'path' => 'api/admin/brands',
//                 'method' => 'post',
//                 'arrange' => '7',
//                 'category' => 'برند ها'],
//             ['title' => 'read_brand',
//                 'descriptiosn' => 'دریافت برند تکی',
//                 'path' => 'api/admin/brands/{id}',
//                 'method' => 'get',
//                 'arrange' => '7',
//                 'category' => 'برند ها'],
//             ['title' => 'update_brand',
//                 'descriptiosn' => 'ویرایش برند',
//                 'path' => 'api/admin/brands/{id}',
//                 'method' => 'post',
//                 'arrange' => '7',
//                 'category' => 'برند ها'],
//             ['title' => 'delete_brand',
//                 'descriptiosn' => 'حذف برند',
//                 'path' => 'api/admin/brands/{id}',
//                 'method' => 'delete',
//                 'arrange' => '7',
//                 'category' => 'برند ها'],
//             ['title' => 'read_guarantees',
//                 'descriptiosn' => 'مشاهده گارانتی ها',
//                 'path' => 'api/admin/guarantees',
//                 'method' => 'get',
//                 'arrange' => '8',
//                 'category' => 'گارانتی ها'],
//             ['title' => 'create_guarantee',
//                 'descriptiosn' => 'افزودن گارانتی',
//                 'path' => 'api/admin/guarantees',
//                 'method' => 'post',
//                 'arrange' => '8',
//                 'category' => 'گارانتی ها'],
//             ['title' => 'read_guarantee',
//                 'descriptiosn' => 'مشاهده گارانتی تکی',
//                 'path' => 'api/admin/guarantees/{id}',
//                 'method' => 'get',
//                 'arrange' => '8',
//                 'category' => 'گارانتی ها'],
//             ['title' => 'update_guarantee',
//                 'descriptiosn' => 'ویرایش گارانتی',
//                 'path' => 'api/admin/guarantees/{id}',
//                 'method' => 'put',
//                 'arrange' => '8',
//                 'category' => 'گارانتی ها'],
//             ['title' => 'delete_guarantee',
//                 'descriptiosn' => 'حذف گارانتی',
//                 'path' => 'api/admin/guarantees/{id}',
//                 'method' => 'delete',
//                 'arrange' => '8',
//                 'category' => 'گارانتی ها'],
//             ['title' => 'read_discounts',
//                 'descriptiosn' => 'مشاهده کد های تخفیف',
//                 'path' => 'api/admin/discounts',
//                 'method' => 'get',
//                 'arrange' => '9',
//                 'category' => 'تخفیف ها'],
//             ['title' => 'create_discount',
//                 'descriptiosn' => 'افزودن کد تخفیف',
//                 'path' => 'api/admin/discounts',
//                 'method' => 'post',
//                 'arrange' => '9',
//                 'category' => 'تخفیف ها'],
//             ['title' => 'update_discount',
//                 'descriptiosn' => 'ویرایش کد تخفیف',
//                 'path' => 'api/admin/discounts/{id}',
//                 'method' => 'put',
//                 'arrange' => '9',
//                 'category' => 'تخفیف ها'],
//             ['title' => 'delete_discount',
//                 'descriptiosn' => 'حذف کد تخفیف',
//                 'path' => 'api/admin/discounts/{id}',
//                 'method' => 'delete',
//                 'arrange' => '9',
//                 'category' => 'تخفیف ها']
//         ]
//     );

//     return 'ok';
// });
